"""Pelican settings for the AssistantAMU documentation site.

The content tree read here is generated by ``build_site.py`` and is not
versioned: run that script rather than ``pelican`` directly.

Paths are absolute, derived from this file, so the build does not depend on the
working directory Read the Docs happens to use.
"""

import json
from pathlib import Path

SITE_DIR = Path(__file__).resolve().parent

# Sections of every page, collected by build_site.py while staging. The sidebar
# draws the whole tree, so rendering one page needs the headings of all of them
# — which Pelican does not expose. Missing file: the sidebar simply stays flat.
try:
    NAV_SECTIONS = json.loads((SITE_DIR / "nav_sections.json").read_text(encoding="utf-8"))
except (OSError, ValueError):
    NAV_SECTIONS = {}

# --- Sources and output -----------------------------------------------------

PATH = str(SITE_DIR / "content")
THEME = str(SITE_DIR / "theme")
PAGE_PATHS = ["pages"]
# No blog in this site. The directory stays empty; naming it keeps Pelican from
# reading the whole content tree as articles.
ARTICLE_PATHS = ["articles"]
# Nothing is copied verbatim any more: the two formerly standalone pages are
# ordinary pages of the site, their body embedded by build_site.py and saved
# under their original file name, so the links written in README.md keep
# resolving. The directory is named all the same, so that adding an image later
# does not require touching this file.
STATIC_PATHS = ["static"]

# --- Addresses --------------------------------------------------------------

# Read the Docs serves each version under a path prefix (/fr/latest/, /fr/v1/…).
# Relative URLs make the site indifferent to the prefix, and let it be opened
# straight from the filesystem.
SITEURL = ""
RELATIVE_URLS = True
PAGE_URL = "{slug}.html"
PAGE_SAVE_AS = "{slug}.html"
# Nothing generates index/archive/tag listings: every page is authored.
DIRECT_TEMPLATES = []
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# --- Identity ---------------------------------------------------------------

SITENAME = "AssistantAMU"
SITESUBTITLE = "Assistant documentaire RAG sur les documents publics d'Aix-Marseille Université"
DEFAULT_LANG = "fr"
TIMEZONE = "Europe/Paris"
LOCALE = ("fr_FR.UTF-8", "fr_FR", "French_France")
REPO_URL = "https://github.com/braurepierre/assistant-amu"

# --- Navigation -------------------------------------------------------------

# Every page carries its own nav_group/nav_order metadata.
NAV_GROUP_TITLES = {"api": "Référence d'API"}

# --- Markdown ---------------------------------------------------------------

MARKDOWN = {
    "extension_configs": {
        # "extra" brings the tables, fenced code blocks, attribute lists and
        # definition lists the existing prose already uses.
        "markdown.extensions.extra": {},
        "markdown.extensions.sane_lists": {},
        "markdown.extensions.codehilite": {"css_class": "highlight", "guess_lang": False},
        # The anchor is rendered at build time rather than by the script: a
        # heading stays linkable on a page whose JavaScript never ran.
        "markdown.extensions.toc": {"permalink": "#", "permalink_title": "Lien vers cette section"},
    },
    "output_format": "html5",
}
