"""Pelican settings for the AssistantAMU documentation site.

The content tree read here is generated by ``build_site.py`` and is not
versioned: run that script rather than ``pelican`` directly.

Paths are absolute, derived from this file, so the build does not depend on the
working directory Read the Docs happens to use.
"""

from pathlib import Path

SITE_DIR = Path(__file__).resolve().parent

# --- Sources and output -----------------------------------------------------

PATH = str(SITE_DIR / "content")
THEME = str(SITE_DIR / "theme")
PAGE_PATHS = ["pages"]
# No blog in this site. The directory stays empty; naming it keeps Pelican from
# reading the whole content tree as articles.
ARTICLE_PATHS = ["articles"]
STATIC_PATHS = ["static"]
# The standalone pages are served at the site root, under their own file name,
# so the links written in README.md resolve once rewritten by build_site.py.
EXTRA_PATH_METADATA = {
    "static/concepts-assistant-amu.html": {"path": "concepts-assistant-amu.html"},
    "static/architecture-assistant-amu.html": {"path": "architecture-assistant-amu.html"},
}

# --- Addresses --------------------------------------------------------------

# Read the Docs serves each version under a path prefix (/fr/latest/, /fr/v1/…).
# Relative URLs make the site indifferent to the prefix, and let it be opened
# straight from the filesystem.
SITEURL = ""
RELATIVE_URLS = True
PAGE_URL = "{slug}.html"
PAGE_SAVE_AS = "{slug}.html"
# Nothing generates index/archive/tag listings: every page is authored.
DIRECT_TEMPLATES = []
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# --- Identity ---------------------------------------------------------------

SITENAME = "AssistantAMU"
SITESUBTITLE = "Assistant documentaire RAG sur les documents publics d'Aix-Marseille Université"
DEFAULT_LANG = "fr"
TIMEZONE = "Europe/Paris"
LOCALE = ("fr_FR.UTF-8", "fr_FR", "French_France")
REPO_URL = "https://github.com/braurepierre/assistant-amu"

# --- Navigation -------------------------------------------------------------

# Prose and API pages carry their own nav_group/nav_order metadata. These two
# entries are the standalone HTML pages, which Pelican only copies.
NAV_GROUP_TITLES = {"api": "Référence d'API"}
NAV_EXTRA_TITLE = "Pages autonomes"
NAV_EXTRA_LINKS = [
    ("concepts-assistant-amu.html", "Page pédagogique"),
    ("architecture-assistant-amu.html", "Carte du code"),
]

# --- Markdown ---------------------------------------------------------------

MARKDOWN = {
    "extension_configs": {
        # "extra" brings the tables, fenced code blocks, attribute lists and
        # definition lists the existing prose already uses.
        "markdown.extensions.extra": {},
        "markdown.extensions.sane_lists": {},
        "markdown.extensions.codehilite": {"css_class": "highlight", "guess_lang": False},
        "markdown.extensions.toc": {"permalink": False},
    },
    "output_format": "html5",
}
